services:
  app:
    image: ghcr.io/excoffierleonard/retrieve
    container_name: retrieve-app
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@db:5432/postgres}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - retrieve

  db:
    image: pgvector/pgvector:pg17
    container_name: retrieve-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - retrieve-db:/var/lib/mysql
    networks:
      - retrieve

volumes:
  retrieve-db:
    name: retrieve-db

networks:
  retrieve:
    name: retrieve